### ISSUE TITLE
cli not working 

### ISSUE THREAD

**Issue by lbrinza** [cdeanj/resistomeanalyzer#2]
Could you please give a complete example of command line. When I'm trying to use ./resistome using  the sam file, fasta reference and the cvs annotation options the output I'm getting is still just the help message.

**Comment by cdeanj** [comment]
I'll fix that right now. Thanks for bringing this to my attention.

**Comment by cdeanj** [comment]
The README has been updated to reflect this. A typical command may look like:
`./resistome -ref_fp ref.fa -sam_fp alignment.sam -annot_fp annotations.csv -gene_fp gene.tsv -group_fp group.tsv -class_fp class.tsv -mech_fp mech.tsv -t 80` 
Please let me know if you encounter any other problems.

Best,
Chris

**Comment by lbrinza** [comment]
Hi Chris, thank you for for your answer. I've updated resistome but still have the problem. Here's the command I'm using and the output.

./resistome -ref_fp megares_database_v1.01.fasta -annot_fp megares_annotations_v1.01.csv -sam_fp artest_MEGARES.processed.sam -gene_fp test_resistomeoutput  -t 80

Program: ResistomeAnalyzer 
Contact: Chris Dean <cdean11@rams.colostate.edu>

Usage: ./resistome [options]

Options:

	-ref_fp		STR/FILE	Fasta formatted reference sequence
	-annot_fp	STR/FILE	CSV formatted annotation database
	-sam_fp		STR/FILE	SAM formatted alignment file
	-gene_fp	STR/FILE	Output name for gene level resistome
	-group_fp	STR/FILE	Output name for group level resistome
	-mech_fp	STR/FILE	Output name for mechanism level resistome
	-class_fp	STR/FILE	Output name for class level resistome
	-t		INT		Gene fraction threshold

**Comment by lbrinza** [comment]
Hi Chris, thank you for for your answer. I've updated resistome but still have the problem. Here's the command I'm using and the output.

./resistome -ref_fp megares_database_v1.01.fasta -annot_fp megares_annotations_v1.01.csv -sam_fp artest_MEGARES.processed.sam -gene_fp test_resistomeoutput -t 80

Program: ResistomeAnalyzer
Contact: Chris Dean cdean11@rams.colostate.edu

Usage: ./resistome [options]

Options:

-ref_fp		STR/FILE	Fasta formatted reference sequence
-annot_fp	STR/FILE	CSV formatted annotation database
-sam_fp		STR/FILE	SAM formatted alignment file
-gene_fp	STR/FILE	Output name for gene level resistome
-group_fp	STR/FILE	Output name for group level resistome
-mech_fp	STR/FILE	Output name for mechanism level resistome
-class_fp	STR/FILE	Output name for class level resistome
-t		INT		Gene fraction threshold

**Comment by cdeanj** [comment]
Yeah, unfortunately, you need to specify all output options for each level (i.e., gene, group, mechanism, class). I'll be making some updates soon to change that.

Best,
Chris

**Comment by lbrinza** [comment]
Oh right, thank you, it works now.
Best,
Lilia

**Comment by cdeanj** [comment]
Awesome!
